name: Deploy to Cloudflare

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-pages:
    concurrency:
      group: pages-prod-main
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy web/ --project-name=oref-map
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  deploy-worker:
    concurrency:
      group: worker-prod-main
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_PROXY }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_PROXY }}
          wranglerVersion: "4"
          command: deploy
          workingDirectory: worker